# Generated by Django 4.1 on 2023-03-24 06:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApp", "0001_add_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="prefectures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "prefectures",
            },
        ),
        migrations.CreateModel(
            name="schools",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                (
                    "prefecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ModelApp.prefectures",
                    ),
                ),
            ],
            options={
                "db_table": "schools",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 24, 6, 51, 56, 57159, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="update_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 24, 6, 51, 56, 57159, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("age", models.IntegerField()),
                ("major", models.CharField(max_length=20)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ModelApp.schools",
                    ),
                ),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
