# Generated by Django 4.1 on 2023-03-26 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApp", "0003_add_place_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "autrhors",
            },
        ),
        migrations.AlterField(
            model_name="person",
            name="create_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 5, 42, 15, 519339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="update_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 3, 26, 5, 42, 15, 519339, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("authors", models.ManyToManyField(to="ModelApp.authors")),
            ],
            options={
                "db_table": "books",
            },
        ),
    ]
